echo Creating server cert...
openssl pkcs12 -export -in ../../certs/certs/server.crt -inkey ../../certs/certs/server.key -out server.pkcs12 -passin pass:server-password -passout pass:server-password -name "Server Cert"

echo Creating truststore...
keytool -import -file ../../certs/certs/rootCA.pem -alias RootCA -keystore trustStore -storepass trust-store-password -noprompt
